# Generated by Django 4.2.2 on 2024-11-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pgsApp", "0008_notification_notification_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[("all", "All Users"), ("specific", "Specific User")],
                default="specific",
                max_length=10,
            ),
        ),
    ]
