# Generated by Django 4.2.2 on 2024-11-01 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pgsApp", "0011_alter_notification_notification_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="message",
            new_name="content",
        ),
        migrations.AlterUniqueTogether(
            name="usernotification",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("all_users", "All Users"),
                    ("specific_user", "Specific User"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pgsApp.notification"
            ),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
