# Generated by Django 4.2.2 on 2024-11-01 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pgsApp", "0012_rename_message_notification_content_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="content",
            new_name="message",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="is_read",
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specific_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_notifications",
                to="pgsApp.notification",
            ),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usernotification",
            unique_together={("user", "notification")},
        ),
    ]
